config/routes.rb
Rails.application.routes.draw do
  get 'lojas/index'
  devise_for :usuarios
  get 'usuarios/perfil'
  resources :usuarios
  root 'lojas#index'
  get '/usuario/avisos', to: 'usuarios#avisos', as: 'avisos'
  get '/usuario/minhas_vendas', to: 'usuarios#minhas_vendas', as: 'minhas_vendas'
  get '/usuario/perfil', to: 'usuarios#perfil', as: 'perfil'
  get '/usuario/configuracao', to: 'usuarios#configuracao', as: 'configuracao'
  put '/usuario/configuracao', to: 'usuarios#update_passworld', as: 'update_passworld'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  enum perfil: %i[admin cliente loja]
  enum status: %i[ativo inativo em_analise recusado]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :email, uniqueness: true
  validates :apelido, uniqueness: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_usuario!
  before_action :verifica_login_usuario
  before_action :configure_permitted_parameters, if: :devise_controller?

 
  def current_ability
    @current_ability ||= Ability.new(current_usuario)
  end

  rescue_from CanCan::AccessDenied do
    users_redirect
  end

  def users_redirect
    if current_usuario.admin?
      redirect_to admin_path
    elsif current_usuario.gerencia?
      redirect_to loja_path
    end
  end

  def verifica_login_usuario
    if usuario_signed_in?
      if current_usuario.inativo?
        Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
        flash[:error] = 'Usuário inativo na plataforma!'
        redirect_to root_path
      end
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:apelido, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:apelido, :email, :password, :current_password)}
  end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  def index
  end
end

app/controllers/usuarios_controller.rb
# frozen_string_literal: true

class UsuariosController < ApplicationController
  def perfil; end

  def configuracao
    @usuario = current_usuario
  end

  def update_passworld
    @usuario = current_usuario

    if @usuario.update(usuario_params.merge(perfil: 1))
      bypass_sign_in(@usuario)
      flash[:success] = 'Senha atualizada!'
      redirect_to root_path
    else
      flash[:error] = 'Senha de confirmação não confere com nova senha!'
      redirect_to configuracao_path
    end
  end

  def minhas_vendas
    @pedidos = Pedido.where(usuario_id: current_usuario.id)
  end

  def usuario_params
    params.require(:usuario).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def number_to_currency_br(number)
    number_to_currency(number, unit: 'R$ ', separator: ',', delimiter: '.')
  end

  def flash_message
    notification = ''
    %i[success info warning error].each do |type|
      next unless flash[type]

      notification += "<script>
        toastr.#{type}('#{flash[type]}')
      </script>"
    end
    notification.html_safe
  end

  def status(status)
    html = ''
    html += if status
              '<span class="badge badge-success">Ativo</span> '
            else
              '<span class="badge badge-danger">Inativo</span> '
            end
    html.html_safe
  end
end

app/helpers/lojas_helper.rb
module LojasHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVaper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', turbolink_track: true %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if usuario_signed_in?%>
    <body>
      <%= flash_message %>
      <%= render 'shared/top_nav' %>
      <div class="page-content">
        <%= render 'shared/side_nav' %>
        <%= yield %>
      </div>
    </body>
    <% else %>
    <body class="layout-boxed-bg">
      <%= flash_message %>
      <%= yield %>
    </body>
    <% end %>
  </body>
</html>

app/views/layouts/shared/_side_nav.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
	<div class="sidebar-mobile-toggler text-center">
		<a href="#" class="sidebar-mobile-main-toggle">
			<i class="icon-arrow-left8"></i>
		</a>
		Navigation
		<a href="#" class="sidebar-mobile-expand">
			<i class="icon-screen-full"></i>
			<i class="icon-screen-normal"></i>
		</a>
	</div>
	<div class="sidebar-content">
		<div class="sidebar-user">
			<div class="card-body">
				<div class="media">
					<div class="mr-3">
						<a href="#"></a>
					</div>
					<div class="media-body">
						<div class="media-title font-weight-semibold"><%#= current_empregado.nome_empregado.capitalize %></div>
						<div class="font-size-xs opacity-50">
							<i class="icon-vcard font-size-sm"></i> <%#= tipo_empregado(current_empregado.tipo_empregado) %> - <%= current_empregado.departamento %>
						</div>
					</div>
					<div class="ml-3 align-self-center">
						<a href="#" class="text-white"><i class="icon-cog3"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="card card-sidebar-mobile">
			<ul class="nav nav-sidebar" data-nav-type="accordion">
				<li class="nav-item-header">
					<div class="text-uppercase font-size-xs line-height-xs">Principal</div> <i class="icon-menu" title="Main"></i>
				</li>
				<li class="nav-item">
				</li>
				<li class="nav-item-header">
					<div class="text-uppercase font-size-xs text-center">
						<%if Rails.env.production? %>
						<!-- toda task feita atualizar versão -->
						<!-- Abaixo U+2193 -->
						versão 1.3 &#10003;	
						<% else %> 
							<%= Rails.env %>
						<% end %>
					</div> <i class="icon-menu" title="Main"></i>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/shared/_top_nav.html.erb
<div class="navbar navbar-expand-md navbar-dark">
	<span class="navbar-brand text-white" style="font-size: 11px;">
		MyVaper
	</span>
	<div class="d-md-none">

		<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
			<i class="icon-paragraph-justify3"></i>
		</button>
	</div>

	<div class="collapse navbar-collapse" id="navbar-mobile">
		<span class="navbar-text ml-md-3 mr-md-auto">
			<span class="text-white">Olá <%#= current_empregado.nome_empregado.capitalize %>, Hoje é <%= Time.now%>.</span>
		</span>
		<ul class="navbar-nav">
			<li class="nav-item dropdown">
				<a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
					<i class="icon-bubbles4"></i>
					<span class="d-md-none ml-2">Avisos</span>
					<!-- <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0"></span> -->
				</a>

				<div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
					<div class="dropdown-content-header">
						<span class="font-weight-semibold">Em breve...</span>
						<a href="#" class="text-default"><i class="icon-compose"></i></a>
					</div>
					<!-- <div class="dropdown-content-body dropdown-scrollable">
						<ul class="media-list">
							<li class="media">
								<div class="mr-3 position-relative">
								</div>

								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">James Alexander</span>
											<span class="text-muted float-right font-size-sm">04:58</span>
										</a>
									</div>

									<span class="text-muted">who knows, maybe that would be the best thing for me...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3 position-relative">
								</div>

								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Margo Baker</span>
											<span class="text-muted float-right font-size-sm">12:16</span>
										</a>
									</div>

									<span class="text-muted">That was something he was unable to do because...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Jeremy Victorino</span>
											<span class="text-muted float-right font-size-sm">22:48</span>
										</a>
									</div>

									<span class="text-muted">But that would be extremely strained and suspicious...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Beatrix Diaz</span>
											<span class="text-muted float-right font-size-sm">Tue</span>
										</a>
									</div>

									<span class="text-muted">What a strenuous career it is that I've chosen...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Richard Vango</span>
											<span class="text-muted float-right font-size-sm">Mon</span>
										</a>
									</div>

									<span class="text-muted">Other travelling salesmen live a life of luxury...</span>
								</div>
							</li>
						</ul>
					</div>
					<div class="dropdown-content-footer justify-content-center p-0">
						<a href="#" class="bg-light text-grey w-100 py-2" data-popup="tooltip" title=""
							data-original-title="Load more"><i class="icon-menu7 d-block top-0"></i></a>
					</div> -->
				</div>
			</li>

			<li class="nav-item dropdown dropdown-user">
				<a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					<span><%#= current_empregado.nome_empregado%></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right">
					<%=  link_to "<i class='icon-user-plus'></i> Meu perfil".html_safe, perfil_path, class:'dropdown-item' %>
	
					<div class="dropdown-divider"></div>
					<%=  link_to "<i class='icon-cog5'></i> Configuração da conta".html_safe, configuracao_path(current_empregado), class:'dropdown-item' %>
					<%= link_to destroy_session_path(current_empregado), :method => 'delete', class: 'dropdown-item' do %>
					<i class="icon-switch2"> </i>Sair
					<% end %>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/lojas/index.html.erb
<h1>Lojas#index</h1>
<p>Find me in app/views/lojas/index.html.erb</p>

app/views/shared/_side_nav.html.erb
<div class="sidebar sidebar-dark sidebar-main sidebar-expand-md">
	<div class="sidebar-mobile-toggler text-center">
		<a href="#" class="sidebar-mobile-main-toggle">
			<i class="icon-arrow-left8"></i>
		</a>
		Navigation
		<a href="#" class="sidebar-mobile-expand">
			<i class="icon-screen-full"></i>
			<i class="icon-screen-normal"></i>
		</a>
	</div>
	<div class="sidebar-content">
		<div class="sidebar-user">
			<div class="card-body">
				<div class="media">
					<div class="mr-3">
						<a href="#"></a>
					</div>
					<div class="media-body">
						<div class="media-title font-weight-semibold"><%= current_usuario.apelido.capitalize %></div>
					</div>
					<div class="ml-3 align-self-center">
						<a href="#" class="text-white"><i class="icon-cog3"></i></a>
					</div>
				</div>
			</div>
		</div>
		<div class="card card-sidebar-mobile">
			<ul class="nav nav-sidebar" data-nav-type="accordion">
				<li class="nav-item-header">
					<div class="text-uppercase font-size-xs line-height-xs">Principal</div> <i class="icon-menu" title="Main"></i>
				</li>
				<li class="nav-item">
				</li>
				<li class="nav-item-header">
					<div class="text-uppercase font-size-xs text-center">
						<%if Rails.env.production? %>
						<!-- toda task feita atualizar versão -->
						<!-- Abaixo U+2193 -->
						versão 0.1 &#10003;	
						<% else %> 
							<%= Rails.env %>
						<% end %>
					</div> <i class="icon-menu" title="Main"></i>
				</li>
			</ul>
		</div>
	</div>
</div>

app/views/shared/_top_nav.html.erb
<div class="navbar navbar-expand-md navbar-dark">
	<span class="navbar-brand text-white" style="font-size: 11px;">
		MyVaper
	</span>
	<div class="d-md-none">

		<button class="navbar-toggler sidebar-mobile-main-toggle" type="button">
			<i class="icon-paragraph-justify3"></i>
		</button>
	</div>

	<div class="collapse navbar-collapse" id="navbar-mobile">
		<span class="navbar-text ml-md-3 mr-md-auto">
			<span class="text-white">Olá <%= current_usuario.apelido.capitalize %>, Hoje é <%= Time.now%>.</span>
		</span>
		<ul class="navbar-nav">
			<li class="nav-item dropdown">
				<a href="#" class="navbar-nav-link dropdown-toggle caret-0" data-toggle="dropdown">
					<i class="icon-bubbles4"></i>
					<span class="d-md-none ml-2">Avisos</span>
					<!-- <span class="badge badge-pill bg-warning-400 ml-auto ml-md-0"></span> -->
				</a>

				<div class="dropdown-menu dropdown-menu-right dropdown-content wmin-md-350">
					<div class="dropdown-content-header">
						<span class="font-weight-semibold">Em breve...</span>
						<a href="#" class="text-default"><i class="icon-compose"></i></a>
					</div>
					<!-- <div class="dropdown-content-body dropdown-scrollable">
						<ul class="media-list">
							<li class="media">
								<div class="mr-3 position-relative">
								</div>

								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">James Alexander</span>
											<span class="text-muted float-right font-size-sm">04:58</span>
										</a>
									</div>

									<span class="text-muted">who knows, maybe that would be the best thing for me...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3 position-relative">
								</div>

								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Margo Baker</span>
											<span class="text-muted float-right font-size-sm">12:16</span>
										</a>
									</div>

									<span class="text-muted">That was something he was unable to do because...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Jeremy Victorino</span>
											<span class="text-muted float-right font-size-sm">22:48</span>
										</a>
									</div>

									<span class="text-muted">But that would be extremely strained and suspicious...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Beatrix Diaz</span>
											<span class="text-muted float-right font-size-sm">Tue</span>
										</a>
									</div>

									<span class="text-muted">What a strenuous career it is that I've chosen...</span>
								</div>
							</li>

							<li class="media">
								<div class="mr-3">
								</div>
								<div class="media-body">
									<div class="media-title">
										<a href="#">
											<span class="font-weight-semibold">Richard Vango</span>
											<span class="text-muted float-right font-size-sm">Mon</span>
										</a>
									</div>

									<span class="text-muted">Other travelling salesmen live a life of luxury...</span>
								</div>
							</li>
						</ul>
					</div>
					<div class="dropdown-content-footer justify-content-center p-0">
						<a href="#" class="bg-light text-grey w-100 py-2" data-popup="tooltip" title=""
							data-original-title="Load more"><i class="icon-menu7 d-block top-0"></i></a>
					</div> -->
				</div>
			</li>

			<li class="nav-item dropdown dropdown-user">
				<a href="#" class="navbar-nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
					<span><%= current_usuario.apelido.capitalize%></span>
				</a>
				<div class="dropdown-menu dropdown-menu-right">
					<%=  link_to "<i class='icon-user-plus'></i> Meu perfil".html_safe, usuarios_perfil_path, class:'dropdown-item' %>
	
					<div class="dropdown-divider"></div>
					<%=  link_to "<i class='icon-cog5'></i> Configuração da conta".html_safe, configuracao_path(current_usuario), class:'dropdown-item' %>
					<%= link_to destroy_session_path(current_usuario), :method => 'delete', class: 'dropdown-item' do %>
					  <i class="icon-switch2"> </i>Sair
					<% end %>
				</div>
			</li>
		</ul>
	</div>
</div>

app/views/usuarios/configuracao.html.erb
<div class="content-wrapper">
  <div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
      <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Meu perfil</span>
        </h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
      </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
      <div class="header-elements d-none">
        <div class="breadcrumb justify-content-center">
          <div class="breadcrumb-elements-item dropdown p-0">
            <a href="/usuario/perfil" class="breadcrumb-elements-item ">
              <i class="icon-user-plus mr-2"></i>
              Perfil
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="d-flex align-items-start flex-column flex-md-row">
      <div class="tab-content w-100 overflow-auto order-2 order-md-1">
        <div class="tab-pane fade active show" id="settings">

          <!-- Profile info -->
          <div class="card">
            <div class="card-header header-elements-inline">
              <h5 class="card-title">Troca senha</h5>
              <div class="header-elements">
                <div class="list-icons">
                  <a class="list-icons-item" data-action="collapse"></a>
                </div>
              </div>
            </div>

            <div class="card-body">
              <%= form_for(@usuario, url: update_passworld_path(current_usuario), html: { method: :put }) do |f| %>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Nova senha</label>
                      <%= f.password_field :password, autocomplete: "Nova senha", class:'form-control' %>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Confirma senha</label>
                      <%= f.password_field :password_confirmation, autocomplete: "repita nova senha", class:'form-control' %>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-6">
                      <%= f.submit "Confirma", class:'btn btn-success' %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/usuarios/perfil.html.erb
<div class="content-wrapper">
  <div class="page-header page-header-light">
    <div class="page-header-content header-elements-md-inline">
      <div class="page-title d-flex">
        <h4><i class="icon-arrow-left52 mr-2"></i> <span class="font-weight-semibold">Meu perfil</span>
        </h4>
        <a href="#" class="header-elements-toggle text-default d-md-none"><i class="icon-more"></i></a>
      </div>
    </div>

    <div class="breadcrumb-line breadcrumb-line-light header-elements-md-inline">
      <div class="header-elements d-none">
        <div class="breadcrumb justify-content-center">
          <div class="breadcrumb-elements-item dropdown p-0">
            <a href="/usuario/configuracao" class="breadcrumb-elements-item ">
              <i class="icon-gear mr-2"></i>
              Configurações
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="content">
    <div class="d-flex align-items-start flex-column flex-md-row">
      <div class="tab-content w-100 overflow-auto order-2 order-md-1">
        <div class="tab-pane fade active show" id="settings">

          <!-- Profile info -->
          <div class="card">
            <div class="card-header header-elements-inline">
              <h5 class="card-title">Informações de perfil</h5>
              <div class="header-elements">
                <div class="list-icons">
                  <a class="list-icons-item" data-action="collapse"></a>
                </div>
              </div>
            </div>

            <div class="card-body">
              <form action="#">
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Apelido</label>
                      <input type="text" class="form-control bg-slate border-slate" value="<%= current_usuario.apelido %>" disabled>
                    </div>
                  </div>
                </div>

                <div class="form-group">
                  <div class="row">
                    <div class="col-md-6">
                      <label>Email</label>
                      <input type="text" readonly="readonly" value="<%= current_usuario.email %>" class="form-control bg-slate border-slate" disabled>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>